### ISSUE TITLE
Wrong behaviour

### ISSUE THREAD

**Issue by 2u4u** [jgoralcz/aki-api#19]
Looks like API is changed. At least when I use online Akinator it shows on question, when I use your package it shows another, repeat always the same questions and same answers

**Comment by jgoralcz** [comment]
I'll be looking into it. Could you give me some example code and example Q/A? Thanks!

**Comment by jgoralcz** [comment]
I believe it is how Akinator uses cookies. If you clear the cookies in every session, it shows some "weird behavior", meaning that some questions are just purely random. This is a result of the akinator. If you have an example, I can look further into this.
