### ISSUE TITLE
KO - ELEM LIST IS EMPTY at win function

### ISSUE THREAD

**Issue by Xenorio** [jgoralcz/aki-api#25]
I know that there is a closed issue with the same error, but i'm getting it while using async/await and not callbacks.

My code looks like this:
```js
while(currentStep.progress <= 85){
        // getAkiAnswer does some unrelated stuff and returns the index of the desired answer
        await bot.tools.getAkiAnswer(bot, msg, currentStep, message, async (answer) => { 
        currentStep = await aki.step(region, akidata.session, akidata.signature, answer, currentStep.nextStep)
    })
}
let win = await aki.win(region, akidata.session, akidata.signature, currentStep.currentStep);
```

And the console screams this at me after the progress is more than 85:
```
(node:15827) UnhandledPromiseRejectionWarning: Unknown error has occured. Server response: KO - ELEM LIST IS EMPTY
```

The steps themselves work fine. The error only comes when the win function executes

Here's some example input if that is relevant in any way:
```
Has your character really existed? => Yes
Is your character's gender female? => No
Does your character have a gaming channel? => No
Is your character a famous youtuber? => No
Does your character create music? => No
Is your character older than 20? => Yes
Is your character linked with sports? => No
Is your character an actor? => No
Did your character die? => No
Does your character personally know you? => No
Does your character live in America? => Yes
Did your character run for president? => Yes
Was your character's hair ever blond? => Yes
-ERROR-
```

I am using the "en" region

**Comment by jgoralcz** [comment]
You are using version 3.0.0? I can't duplicate this hm.

**Comment by Xenorio** [comment]
I literally cloned master into my node_modules folder ¯\_(ツ)_/¯

**Comment by jgoralcz** [comment]
Is it causing this every time? The only thing I can think of is one of the parameters being wrong somehow, causing it to return back nothing as a result, which is why the element list is empty. I uninstalled aki-api@3.0.0 and reinstalled and it seems to work for me. Is this a problem for anyone else as well?

**Comment by Xenorio** [comment]
Yes, it happens every time. Doesn't matter which input i give it.

Also, when i'm logging every step to console it looks perfectly normal.

I have tried every possible version (master branch, development branch, and installing through npm) but no matter what i do, i'm always getting that error.

**Comment by robbymichael1** [comment]
I'm getting it while using async/await and not callbacks too: Server response: KO - ELEM LIST IS EMPTY.
I'm using progress>= 85 too. Using 3.0.0 version (npm install);

**Comment by jgoralcz** [comment]
hmmmm. odd.

**Comment by tatevmejunts** [comment]
Hello everyone. Has anyone solved this issue? I get the same error:
```
Error: Unknown error has occured. Server response: KO - ELEM LIST IS EMPTY
```
It's because guessWin.answers is undefined. Any ideas?

**Comment by tatevmejunts** [comment]
Hello everyone. Has anyone solved this issue? I get the same error:
```
Error: Unknown error has occured. Server response: KO - ELEM LIST IS EMPTY
```
And it's because guessWin.answers is undefined. Any ideas how to solve this?

**Comment by tatevmejunts** [comment]
> Hello everyone. Has anyone solved this issue? I get the same error:
> 
> ```
> Error: Unknown error has occured. Server response: KO - ELEM LIST IS EMPTY
> ```
> 
> And it's because guessWin.answers is undefined. Any ideas how to solve this?

Suddenly noticed `Issue with win function #21` and @jgoralcz answer. Error occurs as in build/test.js `aki.win()` is called with wrong parameters. If you c/p this here is the solution. Tried to call it this way
```
const guessWin = await aki.win(region, startGame.session, startGame.signature, step+1).catch( async (error) => {
		            console.error(error);
		            // your akinator next step logic
		        });
```

Now the only problem is that it always ends up with `I guess: Nothing` :)

**Comment by tatevmejunts** [comment]
> Hello everyone. Has anyone solved this issue? I get the same error:
> 
> ```
> Error: Unknown error has occured. Server response: KO - ELEM LIST IS EMPTY
> ```
> 
> And it's because guessWin.answers is undefined. Any ideas how to solve this?

Suddenly noticed `Issue with win function #21` and @jgoralcz answer. Error occurs as in build/test.js `aki.win()` is called with wrong parameters. If you c/p from this here is the solution. Tried to call it this way
```
const guessWin = await aki.win(region, startGame.session, startGame.signature, step+1).catch( async (error) => {
		            console.error(error);
		            // your akinator next step logic
		        });
```

Now the only problem is that it always ends up with `I guess: Nothing` :)

**Comment by jgoralcz** [comment]
Oh I'm sorry about that. Feel free to make a PR to fix the test cases or add your own. I also added an example of how I use it in the "examples/" directory. Maybe that will help you or other people out in the future.

**Comment by jgoralcz** [comment]
await aki.win(region, akidata.session, akidata.signature, currentStep.currentStep);
should be await aki.win(region, akidata.session, akidata.signature, currentStep.nextStep);

Example will be updated as well to show it working.
