### ISSUE TITLE
German, Dutch, Polish, and French 2 aren't working

### ISSUE THREAD

**Issue by NinjaSnail1080** [jgoralcz/aki-api#26]
I made a Python version of your library here: https://github.com/NinjaSnail1080/akinator.py and recently, someone opened an issue saying that the languages whose servers started with `srv7` didn't work. I tried all the languages and confirmed that this was true, along with `fr2`. Do you happen to know why these servers don't work?

**Comment by jgoralcz** [comment]
They just change their servers randomly. I'll have to update my own in the future. Also, nice job with the API!

**Comment by NinjaSnail1080** [comment]
Thanks! Just curious, where do you get the servers from?

**Comment by jgoralcz** [comment]
You can often find the servers by inspecting the element on the website. They also have a bunch of other servers. I think you can write a script to ping each one, but I don't do that nor advise it because it could have other consequences against you.

**Comment by jgoralcz** [comment]
will be resolving in next update.
