### ISSUE TITLE
Wrong timeout catching

### ISSUE THREAD

**Issue by RocoGreen** [jgoralcz/aki-api#27]
Hello, i have noticed in your code (json.completion === 'KO - TIMED OUT') is incorrect because the api return now: KO - TIMEOUT so the code need to be (json.completion === 'KO - TIMEOUT')
And also if you can, catch the WARN - NO QUESTION 
Can you fix it please ?

**Comment by jgoralcz** [comment]
Yep this will most likely be updated tomorrow, thanks for opening the issue.
