### ISSUE TITLE
New Game always gives KO - KEY NOT FOUND2

### ISSUE THREAD

**Issue by janniksam** [jgoralcz/aki-api#28]
Its not an usual issue, but maybe you can help me anyways.... I'm trying to port your code to c#.
Unfortunately I'm stuck at the error above...

My method is looking like this atm:

```cs
public static string NewGameUrl(ApiKey apiKey, Language language)
{
    var frontAdressEncoded = UpperCaseUrlEncode(apiKey.FrontAdress);
    return
        $"https://{ServerSelector.GetServerFor(language)}/new_session?partner=1&player=website-desktop&uid_ext_session={apiKey.SessionUid}&frontaddr={frontAdressEncoded}&constraint=ETAT%3C%3E%27AV%27&&constraint=ETAT<>'AV'";
}
```

An examplary result of the method is the following (german):

`https://srv14.akinator.com:9283/ws/new_session?partner=1&player=website-desktop&uid_ext_session=ef9fbe2e-b56f-11e9-a04b-0cc47a40ef18&frontaddr=NDYuMTA1LjExMC40NQ%3D%3D&constraint=ETAT%3C%3E%27AV%27&&constraint=ETAT<>'AV'`

It looks fine, doesnt it? The encoding of the front adress seems to be also fine, I compared it to the actual request send by my firefox browser.

But whenever I request that URL, it gives me back:
`{"completion":"KO - KEY NOT FOUND2"}`

Do you know, what the mistake could be? Could you give me an exact formula for the URL including all the params I need to set? 

Thanks in advance! :)

**Comment by jgoralcz** [comment]
There are a few servers that I'm not sure why they don't work. One is Russia, which has that same issue. I more or less follow what the akinator website has, inspect element, go to their scripts, find something that looks like srv, follow that then play around with it. I'm still trying to track down a solution for that.

**Comment by janniksam** [comment]
I saw, that the animal server actually did work in german, but not the person one. Really weird. Its the same server shown in my inspect tool...

**Another unrelated question:**

How does the Akinator show you his first guess, or when does Akinator guess in general? I mean, when you play on the website, there comes the moment, he does guess. Is that point a absolute point in time / when he exceeds a specific percentage?

**Comment by jgoralcz** [comment]
I figured out the problem with the servers, hopefully have an update tomorrow addressing that.

And yes, to track his guess, you use the `progress` property and check if above your threshold from 0 to 1. I like to do around 0.7. I believe there may be a problem if you do it too early.

**Comment by thebitler** [comment]
Same for me, for anyone server
