### ISSUE TITLE
fr_2 | fr_objects_2 | fr_animals_2 available

### ISSUE THREAD

**Issue by RocoGreen** [jgoralcz/aki-api#29]
Uhh i noticed in the night, the akinator servers in the module say down so i checked in the fr site and i noticed an alternative for fr servers and it's :

fr : srv12.akinator.com:9185
fr_objects : srv3.akinator.com:9218
fr_animals : srv3.akinator.com:9259

Please can you add that ?

**Comment by jgoralcz** [comment]
Feel free to make a pull request, or I'll get to it when I have time.
Thanks for pointing this out!
