### ISSUE TITLE
Error: A problem occurred with making the request.

### ISSUE THREAD

**Issue by Pneuma714** [jgoralcz/aki-api#34]
This error occurred when aki.start('kr') runs.

(node:19424) UnhandledPromiseRejectionWarning: Error: A problem occurred with making the request.
Request Value: null
    at rp (C:\Users\syca0\Desktop\Pod\node_modules\aki-api\src\lib\functions\Request.js:25:11)
    at async module.exports (C:\Users\syca0\Desktop\Pod\node_modules\aki-api\src\functions\start.js:17:18)
    at async Object.execute (C:\Users\syca0\Desktop\Pod\commands\Fun\akinator.js:20:18)
(node:19424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by ObiDriftKenobi** [comment]
Same with en

**Comment by jgoralcz** [comment]
v4.0.0 should be fixing this. Thanks for being patient.
