### ISSUE TITLE
A problem occurred with making the request: TypeError: result.data.indexOf is not a function

### ISSUE THREAD

**Issue by dragonfire535** [jgoralcz/aki-api#72]
The error is coming from here:
https://github.com/jgoralcz/aki-api/blob/c70dedebe085a44165636b60394e27644c1337cf/src/lib/functions/Request.js#L22-L35
So I assume the request is returning either nothing or something different than you're expecting. Probably another API change.

**Comment by jgoralcz** [comment]
Yea it's probably another API change. I haven't figured out what it is yet though

**Comment by jgoralcz** [comment]
So I didn't really do any changes besides an error message accounting for a lack of data from akinator. I believe this happened because akinator was having problems and was slow during that week. I think it took over a minute to even load the page.
