### ISSUE TITLE
Your Akinator session has timed out. KO - TIMEOUT

### ISSUE THREAD

**Issue by HellLover** [jgoralcz/aki-api#74]
Hello. I have a problem when running the aki command, so it says **Your Akinator session has timed out. KO - TIMEOUT**. I want to know, is that api issue, or something from me? Thank you for answer.

**Comment by jgoralcz** [comment]
There is a big problem with how this module interacts with aki atm. If that is solved, it may solve this.

**Comment by jgoralcz** [comment]
The KO - TIMEOUT was actually correct for the time. I believe this happened because the akinator site was having problems and was slow during that week. I think it took over a minute to even load the page.
