### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by Ult1m1** [jgoralcz/aki-api#80]
Hi, will add more languages?

**Comment by jgoralcz** [comment]
Which languages?

You can technically add any language without modifying the library as well by putting the region abbreviation from akinator as the region.

Feel free to make a pull request to add more languages

**Comment by Ult1m1** [comment]
I would like him to have a Czech language (cz)

**Comment by jgoralcz** [comment]
I am not the creator of akinator.com. I don't make those decisions. This is simply a library to interact with their service. Once they support it, we can add it here. However, they do not have it yet.
